name: Update README Banner

on:
  schedule:
    - cron: "*/5 * * * *"   
  workflow_dispatch:        

jobs:
  update-banner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run update script
        run: python scripts/update_banner.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update banner image" || echo "No changes to commit"
          git push
